### ISSUE TITLE
为什么返回都是null

### ISSUE THREAD

**Issue by rlog** [dcloudio/H5P.Server#1]
我在配置 wexinpay v3 , 已经把config改成我自己的信息了，但访问时很多内容返回都是null。可能是那里的问题呢？

http://hbpay.sinaapp.com/wxpayv3/index.php

**Comment by YanYL** [comment]
可能是服务器上php对某些API不支持，建议在本地使用php调试确认。



yanyilin@dcloud.io
 
发件人： Robin Deng
发送时间： 2015-06-22 23:50
收件人： dcloudio/H5P.Server
主题： [H5P.Server] 为什么返回都是null (#1)
我在配置 wexinpay v3 , 已经把config改成我自己的信息了，但访问时很多内容返回都是null。可能是那里的问题呢？
http://hbpay.sinaapp.com/wxpayv3/index.php

**Comment by rlog** [comment]
@YanYL 我在本地跑回报这些错误：

```
Notice: Undefined index: appid in D:\usbwebserver\root\wxpay\WxPay.Api.php on line 71
Notice: Undefined index: mch_id in D:\usbwebserver\root\wxpay\WxPay.Api.php on line 72
Notice: Undefined index: prepay_id in D:\usbwebserver\root\wxpay\WxPay.Api.php on line 73
Notice: Undefined index: nonce_str in D:\usbwebserver\root\wxpay\WxPay.Api.php on line 74
```

**Comment by rlog** [comment]
一直返回

```
array(2) {
  ["return_code"]=>
  string(4) "FAIL"
  ["return_msg"]=>
  string(24) "支付权限检查失败"
}
```
