### ISSUE TITLE
微信支付 官方并没有C#.NET服务端的示例，我写了一个，是否可以发在这里？

### ISSUE THREAD

**Issue by xland** [dcloudio/H5P.Server#2]
微信支付 官方并没有C#.NET服务端的示例，我写了一个，是否可以发在这里？

**Comment by YanYL** [comment]
非常感谢，已经邀请你加入到此项目中。

**Comment by xland** [comment]
OK~
我尽快写好，发出来

**Comment by xland** [comment]
@YanYL 

我代码已经写好了，请问是否可以授权给我，我独立创建一个项目
这样就不用和PHP的DEMO代码混合在一起了

**Comment by xland** [comment]
@YanYL 
或者我发到我自己的名字下面，
然后在咱们项目的readme里加一段说明，再附上一个链接，
你们看怎么操作合适~

**Comment by YanYL** [comment]
可以，就把C#源码独立一个项目放到你自己名下
然后在readme中加说明及链接，在你项目的readme中也加个说明链接回来
我已经邀请你到这个项目中了，可以直接修改readme提交

**Comment by xland** [comment]
@YanYL 

以更新，我关掉这个issue了
